### ISSUE TITLE
Ability to retrieve all presets and sound processing modes

### ISSUE THREAD

**Issue by conrad-nash** [binarylogic/trinnov-altitude-homeassistant#6]
Not a bug, a feature request. Is there a way to retrieve the available presets from the Trinnov and display them in a dropdown? Same for the sound processing modes.

It would be great to be able to have that so I can pass them to my remote2.

Awesome work on the integration, it's working well here - thank you.

**Comment by binarylogic** [comment]
Hi @conrad-nash , sorry I missed this. Yes, that should be possible. I've noticed that the media player dropdown in Home Assistant isn't populating properly. I'll take a look and update this issue if/when I can fix this.

**Comment by djgigi** [comment]
Hi, in effects delete application.
I also use your code with the UC remote 2 and HA, I can turn my altitude on/off, change the volume, but it's impossible to change the input with the Unfolded Circle remote 2, but it doesn't work via HA directly with this script either, 

`   trinnov_input_1:
      alias: "Trinnov Input 1"
      sequence:
        - service: remote.send_command
          target:
            entity_id: remote.trinnov_altitude
          data:
            command:
              - source_set 1`
              
Am I the only one with this problem?

**Comment by binarylogic** [comment]
Hm, your script looks good. Here's mine, which works fine. You might consider adding the same options:

```yaml
-   service: remote.send_command
    data:
      num_repeats: 2
      delay_secs: 10
      hold_secs: 0
      command:
        - source_set 2
        - preset_set 1
        - volume_set -20.0
    target:
      entity_id: remote.media_room_trinnov_altitude
```

`num_repeats` is probably unnecessary, but I set my automations to be idempotent, so I use it as a failsafe.
